# Generated by Django 2.0.7 on 2018-08-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_full',
            field=models.ImageField(blank=True, help_text='Will be auto-generated from image_raw; leave blank', null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_thumbnail',
            field=models.ImageField(blank=True, help_text='Will be auto-generated from image_raw; leave blank', null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_thumbnail_transparent',
            field=models.ImageField(blank=True, help_text='Will be auto-generated from image_raw; leave blank', null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_full',
            field=models.ImageField(blank=True, help_text='A good-sized version of the base image. Will be auto-generated from image_raw; leave blank', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_raw',
            field=models.ImageField(blank=True, help_text='A base image that will be manipulated to generate other image fields.', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_thumbnail',
            field=models.ImageField(blank=True, help_text='A smaller version of the base image. Will be auto-generated from image_raw; leave blank', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_thumbnail_transparent',
            field=models.ImageField(blank=True, help_text='A smaller version of the base image, with an alpha layer. Will be auto-generated from image_raw; leave blank', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(default='', help_text='A short description of the series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_full',
            field=models.ImageField(blank=True, help_text='A good-sized version of the base image. Will be auto-generated from image_raw; leave blank', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_raw',
            field=models.ImageField(blank=True, help_text='A base image that will be manipulated to generate other image fields.', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_thumbnail',
            field=models.ImageField(blank=True, help_text='A smaller version of the base image. Will be auto-generated from image_raw; leave blank', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_thumbnail_transparent',
            field=models.ImageField(blank=True, help_text='A smaller version of the base image, with an alpha layer. Will be auto-generated from image_raw; leave blank', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='latest_article_date',
            field=models.DateTimeField(blank=True, help_text='The date and time the newest Article of this Series was published. Will be set automatically when an Article is created.', null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Tags used to help search for articles.', max_length=200, unique=True),
        ),
    ]
