# Generated by Django 2.0 on 2018-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(help_text='The series this article should be filed under; will be used for URLs', max_length=40, unique=True),
        ),
    ]
