# Generated by Django 2.0.7 on 2018-07-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180730_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
