# Generated by Django 2.0.7 on 2018-08-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20180807_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_thumbnail_transparent',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='author',
            name='image_thumbnail_transparent',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='series',
            name='image_thumbnail_transparent',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/'),
        ),
    ]
