# Generated by Django 2.0.7 on 2018-08-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20180807_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/audio'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_full',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_raw',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_thumbnail_transparent',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_full',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_thumbnail_transparent',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_full',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_raw',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_thumbnail_transparent',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='uploads/'),
        ),
    ]
