# Generated by Django 2.0 on 2018-02-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_modifed',
            new_name='date_modified',
        ),
    ]
