# Generated by Django 2.0 on 2018-02-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180215_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(default='misc', help_text='The short version of the name to use in URLs'),
        ),
    ]
