# Generated by Django 2.0 on 2018-02-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180216_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', help_text='A no space name to be used for URLs'),
        ),
    ]
