# Generated by Django 2.0.7 on 2018-07-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180216_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date', '-date_modified']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'series'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_posted',
            new_name='publish_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Unlimited length. HTML formatted.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Slugs are short versions of the title used for URLs', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='A no space name to be used for URLs', null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='The short version of the name to use in URLs', null=True),
        ),
    ]
