# Generated by Django 2.0.7 on 2018-07-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_series_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-latest_article_date'], 'verbose_name_plural': 'series'},
        ),
        migrations.AddField(
            model_name='series',
            name='latest_article_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
