# Generated by Django 2.0.7 on 2018-08-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20180731_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-latest_article__date'], 'verbose_name_plural': 'series'},
        ),
    ]
