# Generated by Django 2.0.7 on 2018-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20180807_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image_raw',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='image',
            new_name='image_raw',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='image',
            new_name='image_raw',
        ),
        migrations.RemoveField(
            model_name='author',
            name='modelwithimages_ptr',
        ),
        migrations.AddField(
            model_name='article',
            name='image_full',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='image_full',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='author',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='series',
            name='image_full',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='series',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='ModelWithImages',
        ),
    ]
